In [11]:
import numpy as np

In [12]:
import pandas as pd

In [13]:
import pandas as pd

file_path = r"C:\Users\Arcite\Downloads\stud-dataset.csv"

df = pd.read_csv(file_path)

print(df.head())

   id             name               nationality                 city  \
0   0        Kiana Lor                     China               Suzhou
1   1   Joshua Lonaker  United States of America        Santa Clarita
2   2    Dakota Blanco  United States of America              Oakland
3   3  Natasha Yarusso  United States of America        Castro Valley
4   4   Brooke Cazares                    Brazil  São José dos Campos

   latitude  longitude gender  ethnic.group  age  english.grade  math.grade  \
0     31.31     120.62      F           NaN   22            3.5         3.7
1     34.39    -118.54      M           NaN   22            2.9         3.2
2     37.80    -122.27      F           NaN   22            3.9         3.8
3     37.69    -122.09      F           NaN   20            3.3         2.8
4    -23.18     -45.88      F           NaN   21            3.7         2.6

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0
2             3.2             5.0                 3                 3.0
3             3.2             5.0                 5                 2.0
4             3.4             1.0                 4                 4.0

   refletter.rating
0                 4
1                 5
2                 4
3                 4
4                 5

In [14]:
df.index

RangeIndex(start=0, stop=307, step=1)

In [15]:
df.columns

Index(['id', 'name', 'nationality', 'city', 'latitude', 'longitude', 'gender',
       'ethnic.group', 'age', 'english.grade', 'math.grade', 'sciences.grade',
       'language.grade', 'portfolio.rating', 'coverletter.rating',
       'refletter.rating'],
      dtype='str')

In [16]:
df.values

array([[0, 'Kiana Lor', 'China', ..., 4, 4.0, 4],
       [1, 'Joshua Lonaker', 'United States of America', ..., 5, 4.0, 5],
       [2, 'Dakota Blanco', 'United States of America', ..., 3, 3.0, 4],
       ...,
       [304, 'Zachary Mulvahill', 'United States of America', ..., 5,
        5.0, 3],
       [305, 'Eliana Michelsen', 'United States of America', ..., 4, 4.0,
        5],
       [306, 'Dane Whittemore', 'Canada', ..., 5, 4.0, 5]],
      shape=(307, 16), dtype=object)

In [17]:
df.axes

[RangeIndex(start=0, stop=307, step=1),
 Index(['id', 'name', 'nationality', 'city', 'latitude', 'longitude', 'gender',
        'ethnic.group', 'age', 'english.grade', 'math.grade', 'sciences.grade',
        'language.grade', 'portfolio.rating', 'coverletter.rating',
        'refletter.rating'],
       dtype='str')]

In [18]:
df.ndim

2

In [19]:
df.size

4912

In [20]:
df.memory_usage(deep=True)

Index                   132
id                     2456
name                  19392
nationality           20501
city                  17895
latitude               2456
longitude              2456
gender                15366
ethnic.group           2456
age                    2456
english.grade          2456
math.grade             2456
sciences.grade         2456
language.grade         2456
portfolio.rating       2456
coverletter.rating     2456
refletter.rating       2456
dtype: int64

In [21]:
df.empty

False

In [26]:
df.loc[df["id"] > 6]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
7,7,Preston Suarez,Brazil,São Paulo,-23.47,-46.67,M,NaN,22,3.8,3.7,3.6,2.0,5,5.0,4
8,8,Lee Dong,Philippines,Manila,14.60,120.98,F,NaN,24,3.9,3.6,3.2,2.0,4,3.0,5
9,9,Maa'iz al-Dia,Turkey,Istanbul,41.02,28.96,M,NaN,22,2.4,2.8,3.8,3.0,5,5.0,4
10,10,Maja Nicholson,United States of America,Dallas,32.78,-96.80,F,NaN,23,3.4,3.5,3.2,5.0,4,2.0,5
11,11,Sasha Jansen,United States of America,Chicago,41.85,-87.65,F,NaN,21,1.7,4.0,3.6,5.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

In [30]:
df.loc[df["english.grade"] > 6]

Empty DataFrame
Columns: [id, name, nationality, city, latitude, longitude, gender, ethnic.group, age, english.grade, math.grade, sciences.grade, language.grade, portfolio.rating, coverletter.rating, refletter.rating]
Index: []

In [31]:


df.loc[df["sciences.grade"] > 24]

Empty DataFrame
Columns: [id, name, nationality, city, latitude, longitude, gender, ethnic.group, age, english.grade, math.grade, sciences.grade, language.grade, portfolio.rating, coverletter.rating, refletter.rating]
Index: []

In [32]:
df.iloc[[0]]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4

In [33]:
df.iloc[[0, 1]]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5

In [34]:
df.iloc[:3]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4

In [35]:
df.iloc[[0, 2], [1, 3]]

            name     city
0      Kiana Lor   Suzhou
2  Dakota Blanco  Oakland

In [36]:
df.iloc[1:3, 0:3]

   id            name               nationality
1   1  Joshua Lonaker  United States of America
2   2   Dakota Blanco  United States of America